[project]
name = "notification-services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aio-pika>=10.0.1",
    "aiosmtplib>=5.1.2",
    "contracts",
    "fastapi>=0.139.0",
    "jinja2>=3.1.6",
    "pydantic-settings>=2.14.2",
    "uvicorn>=0.51.0",
]

[tool.uv.sources]
contracts = { path = "../contracts", editable = true }
